# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d376bdf47fd627434670922ec01da1a821a4c683c77760ca251e327daec8cdf4fbf5d9bae73d297d44723913d9f0414ac63e31daab637b4e140f14dccd469e35

test:
  secret_key_base: ed6dc10fb0de66c65224b1e67717151da8d9808af646e6e9a65acc4a98e3520eb98b464187be2b83d35730e63ebbf39e429e97eaf5fc2f2fcad29d5b0f68d439

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
